config/routes.rb
StaffingApp::Application.routes.draw do  

  root :to => 'sessions#new'

  resources :candidates_profiles

  get "email/remind"

  post "email/remind"

  resources :admin_users do
  end

  resources :candidates do
    member do
      get :following, :followers, :change, :index
      post :change
    end
    collection do
      get 'search'
    end

  end

  resources :pages do
    collection do
      get 'search'
    end
  end
  
  resources :ExportExcel  
  
  resources :candidates do
    resources :candidate_certifications
    resources :candidates_profiles
    resources :candidate_profile_tags
  end

  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :reply, :update, :feed_micropost, :destroy]
  
  resources :followings do
    collection do 
       post  'follow'
    end
  end

  resources :resume
  resources :candidate_prof_summaries do
    collection do
      get 'destroy'
      post 'destroy'
    end
  end

  resources :candidate_certifications do
    collection do
      get 'destroy'
      post 'destroy'
    end
  end  

  resources :jobs

  match "staff/:id/job_match"=>'job_match#index'
  match "staff/:id/job_match/index"=>'job_match#index'
  #match "/job_match"=>'job_match#match'
  match "/job_match/search/:jobSearch"=>'job_match#search'
  match "/job_match/match/:jobSearch/:matchPercentage"=>'job_match#match'
  match "/job_match/match" =>'job_match#match'
  #match "/job_match/autocomplete" => 'job_match#autocomplete'
  #match "candidates/:id/job_match/information" => 'job_match#information'
  #match "/job_match/match/:jobSearch/:matchPercentage"=>'job_match#match'
  #match "/job_match/match/:matchPercentage" =>'job_match#match'

  #Added
  match "/staff/:id/certifications/action" => 'certifications#action'
  match "/staff/:id/certifications/new" => 'certifications#new'
  match "/staff/:id/certifications/create" => 'certifications#create'
  match "/staff/:id/admin_users" => 'admin_users#index'

  match "staff/:id/jobs"=>'jobs#index'  
  match "staff/:id/jobs/index"=>'jobs#index'
  match "staff/:id/jobs/new"=>'jobs#new'
  match "staff/:id/jobs/edit"=>'jobs#edit'
  match "staff/:id/jobs/create"=>'jobs#create'
  match "staff/:id/jobs/:job_id/edit"=>'jobs#edit'
  match "staff/:id/jobs/:job_id/update"=>'jobs#update'
  match "staff/:id/jobs/:job_id/delete"=>'jobs#destroy'
  match "staff/:id/jobs/:job_id/assign/:candidate_id"=>'jobs#assign'
  match "staff/:id/jobs/:job_id/duplicate"=>'jobs#duplicate'


  match "admin_users/:id/edit/:role" => 'admin_users#edit'
  match "admin_users/new/:letra" => 'admin_users#new'
  match "admin_users/:id/add" => 'admin_users#add'
  match "admin_users/search/:txt" => 'admin_users#search'

  match "interviewer_user/:interviewer_id/new/:letra" => 'interviewer_user#new'
  match "interviewer_user/:interviewer_id/new" => 'interviewer_user#new'
  match "interviewer_user/:interviewer_id/add/:candidate_id" => 'interviewer_user#add'

  match '/signup',  :to => 'candidates#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'

  #microposts
  match "/candidates/:id/followings" => 'followings#follow'
  match "/candidates/:id/unfollow" => 'followings#destroy'
  match "/candidates/:id/profiles" => 'candidates#profiles'
  #match "/candidates/:id/microposts" => 'microposts#create'

  match "/reply/:id" => 'microposts#reply'
  match "/reply" => 'microposts#reply'
  match "/microposts/:id" => 'microposts#update'
  match "/feed_admin/:id" => 'microposts#feed_micropost'
  match "/candidates/:id/wall" => 'user_walls#show' 

  #Resume
  match "/candidates/:id/resume" => 'resume#index'
  match "/candidates/:id/resume/staff_update" => 'resume#staff_update'
  match "/candidates/:id/resume/summary" => 'resume#summary'
  match "/candidates/:id/resume/experience" => 'resume#experience'
  match "/candidates/:id/resume/experience/new" => 'experiences#new'
  match "/candidates/:id/resume/experience/:experience_id/skills/new" => 'experiences#skill'
  match "/experiences/:id/destroy" => 'experiences#destroy'
  match "/candidates/:id/resume/experience/:experience_id/details/new" => 'experience_details#new'
  #match "/resume_details/:id/destro" => 'resume_details#destro'
  match "/candidate_prof_summaries/destro" => 'candidate_prof_summaries#destro'
  #match "/resume_details/:id/destroy" => resume_details_destroy_path
  #match "/candidates/:id/resume/education" => 'resume#education'
#  match "/education/destroy" => 'educations#destroy'

  # Projects
  match "/candidates/:id/projects" => 'projects#index'
  match "/candidates/:id/projects/profile" => 'projects#profile'
  match "/candidates/:id/projects/projects/profile" => 'projects#profile'
  match "/candidates/:id/projects/buildprofile" => 'projects#buildprofile'
  match "/candidates/:id/projects/projects/buildprofile" => 'projects#buildprofile'
  match "/candidates/:id/projects/techs" => 'projects#techs'
  match "/candidates/:id/projects/techs/save" => 'projects#techs_save'
  match "/candidates/:id/project/:project_id/projects/techs" => 'projects#techs'
  match "/candidates/:id/project/:project_id/projects/techs/save" => 'projects#techs_save'
  match "/candidates/:id/projects/new" => 'projects#new'
  match "/candidates/:id/project/:project_id/update" => 'projects#update'
  match "/candidates/:id/project/:project_id/show" => 'projects#show'
  match "/candidates/:id/project/:project_id/destroy" => 'projects#destroy'

  ## Project Roles
  match "/candidates/:id/project/:project_id/projects_roles/new" => 'projects_roles#new'

  #match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/update" => 'projects_roles#update'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/show" => 'projects_roles#show'
  #match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/destroy" => 'projects_roles#destroy'

  #Added
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/role/:role_id/destroy" => 'projects_roles#destroy'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/role/:role_id/update" => 'projects_roles#update'

  ## Project Responsibilities
  #match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/roles_responsibilities/new" => 'roles_responsibilities#new'
  #match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/role/:role_id/roles_responsibilities/new" => 'roles_responsibilities#new'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/roles_responsibilities/:rolerespon_id/destroy" => 'roles_responsibilities#destroy'

  #Added
  match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/roles/:role_id/roles_responsibilities/new" => 'roles_responsibilities#new'

  ## Project Tags
  match "/candidates/:id/projects/:project_id/projects_roles/:projects_role_id/projects_tags/:type_id/new" => 'projects_tags#new'
  match "/candidates/:id/project/:project_id/projects_role/:projects_role_id/projects_tags/:projtag_id/destroy" => 'projects_tags#destroy'
  
  # Education
  match "/education/:id" => 'education#index', :as => :candidate_education
  match "/education/destroy" => 'candidate_education#destroy'
  match "/candidates/:id/resume/education" => 'candidate_education#index'
  match "/candidates/:id/resume/education/new" => 'candidate_education#new'
  match "/candidates/:id/resume/education/create" => 'candidate_education#create', :as => :candidate_education_index
  match "/candidates/:id/resume/education/edit" => 'candidate_education#edit'
  match "/candidates/:id/resume/education/update" => 'candidate_education#update'
  match "/candidates/:id/resume/education/destroy" => 'candidate_education#destroy'
  match "/candidates/:id/education_degrees" => 'educ_degrees#index'
  match "/candidates/:id/education_degrees/new" => 'educ_degrees#new'
  match "/candidates/:id/education_degrees/create" => 'educ_degrees#create'
  match "/candidates/:id/education_degrees/edit" => 'educ_degrees#edit'
  match "/candidates/:id/education_degrees/update" => 'educ_degrees#update'
  match "/candidates/:id/education_degrees/destroy" => 'educ_degrees#destroy'
  match "/candidates/:id/education_degrees/action" => 'educ_degrees#action'

  match "/candidates/:id/candidate_certifications/new" => 'candidate_certifications#new'

  # Candidate
  match "/staff/:id/candidates" => 'staff_candidates#index'
  match "/staff/:id/candidates/detail" => 'staff_candidates#search'

  # Candidate Status
  match "/staff/:id/candidate_status" => 'status#index'
  match "/staff/:id/candidate_status/create" => 'status#create'
  match "/staff/:id/candidate_status/destroy" => 'status#destroy'

  # Interviewers
  match "/staff/:id/interviewers" => 'interviewers#index'
  match "/staff/:id/interviewers/new" => 'interviewers#new'
  match "/staff/:id/interviewers/:interviewer_id/edit" => 'interviewers#edit', :as => :interviewer
  match "/staff/:id/interviewers/:interviewer_id/delete" => 'interviewers#delete'

  # Candidate Certification
  match "/candidates/:id/certification" => 'candidate_certification#index'
  #match "/candidates/:id/resume/certification/new" => 'candidate_certification#new'
  match "/candidate_certifications/destro" => 'candidate_certifications#destro'
  #match "/resume_details/destro" => 'resume_details#destro'
  
  # Certifications
  match "/staff/:id/certifications" => 'certifications#index'
  match "/staff/:id/certifications/action" => 'certifications#action'
  match "/staff/:id/certifications/new" => 'certifications#new'
  match "/staff/:id/certifications/:certification_id/edit" => 'certifications#edit'
  match "/staff/:id/certifications/:certification_id/delete" => 'certifications#delete'
  
  # Roles
  match "/staff/:id/roles" => 'roles#index'

app/views/shared/_admin_feed.html.haml
- if @page_results2 != nil
  - unless @page_results2.empty?
    #checkbox_container    
      %l Show only my conversations with selected candidate?
      = check_box_tag "only_my_posts"
    %br
    %br
    #select_container
      %l Select a candidate to show their posts
      %br
      %br
      = select_tag "select_follower", options_for_select(@page_results2.collect{ |u| [(u.first_name + " " + u.first_last_name), u.id] }), :prompt => "Select a Candidate"
      #loading_image
        = image_tag "ajax-loader.gif"
    #pages_script
    #microposts_feed
    #pages_container

app/views/shared/_admin_sidebar_signed.html.haml
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    Profile Information
  #if_subnav.divider
    - if signed_in?
      #sidebar-profile
        #sidebar-gravatar
          =link_to("#") do
            = image_tag @candidate.avatarurl
        #sidebar-candidate
          = current_candidate.first_name
          = current_candidate.first_last_name
      %br
    %br
    -if has_admin_role?
      
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_candidates('Candidates', current_candidate.id, :action => 'candidates', :class => 'profile-sub_navigation')
        %li
          %i.iconReport
          = link_to 'Advanced search', '/staff/' + current_candidate.id.to_s + '/report', :class => 'profile-sub_navigation'
        %li
          %i.iconSummary
            = label_tag 'Catalogs', nil, :class => 'profile-sub_navigation'
          %br
          %br
          %ul#nav_sub.sub_navigation
            //%li
            //  %i.iconStatus
            //  = link_to 'Candidate Status', '/staff/' + current_candidate.id.to_s() + '/candidate_status', :class => 'profile-sub_navigation'
            %li
              %i.iconIntervieweType
              = link_to "Interview Types", url_options = { :controller => "interviews_types", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconInterviewer
              = link_to "Interviewers", url_options = { :controller => "interviewers", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconEducation
              = link_to 'Education Degrees', url_options = {:controller => "educ_degrees",:action => 'index', :id => current_candidate.id},  :class => 'profile-sub_navigation'
            %li
              %i.iconInterests
              = link_to 'Languages', '/staff/' + current_candidate.id.to_s + '/languages', :class => 'profile-sub_navigation'
            %li
              %i.iconCertification
              = link_to "Certifications", url_options = { :controller => "certifications", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconRolesHeadLine{:style => 'margin-top: 8px;'}
              = link_to "Roles", url_options = { :controller => "roles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Knowledges", url_options = { :controller => "tags", :action => "Knowledges", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Tools", url_options = { :controller => "tags", :action => "Knowledges", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Platforms", url_options = { :controller => "tags", :action => "Knowledges", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
    -else
      %ul#nav_sub.sub_navigation

        // - if is_follow?(@candidate.id)
        = link_to('send Message', '#', html_options = {:id => "send_message", :class=>"show_hide", :rel=>"#slidingDiv"})
        #flash
          - flash.each do |key, value|
            .flash{:class => key} = value
        %div#slidingDiv
          = form_for(:microposts, :url=>{:controller => "microposts", :action=>'create'}, :html => {:id => "createMicroPostForm"}) do |f|
            = hidden_field_tag :candidate_id , @candidate.id
            = text_area_tag "message_text"
            = submit_tag "Send", :class => "btn btn-primary"
        %div#emptyDiv
        %br
        %br
        = link_to 'Return Home', root_path, :class => "profile-sub_navigation"
        %h4 "Edit as #{current_candidate.first_name} #{current_candidate.first_last_name}" 
        %li
          %i.iconContact-info
          = link_to 'Profile', edit_candidate_path(@candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_resume('Resume', @candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
          %ul#nav_sub.sub_navigation
            %li
              %i.iconSummary
              = link_to_resume('Summary', @candidate.id, :action => 'summary', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_project('Projects', @candidate.id, :action => 'index', :class => 'profile-sub_navigation')
            %li
              %i.iconEducation
              = link_to_resume('Education', @candidate.id, :action => 'education', :class => 'profile-sub_navigation')
            %li
              %i.iconCertification
              = link_to_resume('Certification', @candidate.id, :action => 'certification', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_resume('Candidate Profiles', @candidate.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
            %li.last
              %i.iconInterests
              = link_to_resume('Languages', @candidate.id, :action => 'languages', :class => 'profile-sub_navigation')
    %br
    .clear

app/views/shared/_error_messages.html.haml
- unless @error.nil?
  - if @error.any?
    #error_explanation
      %h2
        = pluralize(object.errors.count, "error")
        prohibited this 
        = object.class.to_s.underscore.humanize.downcase
        from being saved:
      %p 
        There were problems with the following fields: 
        %ul
          - object.errors.full_messages.each do |msg| 
            %li= msg

app/views/shared/_feed.html.haml
- unless @page_results.empty?
  %table{:class => 'microposts'}
    = render :partial => 'shared/feed_item', :collection => @page_results
  %br
  #feed-pagination
    = will_paginate @page_results

app/views/shared/_feed_item.html.haml
- sender = Candidate.find(feed_item.created_by)
- receiver = Candidate.find(feed_item.candidate_id)
- if (!feed_item.checked? && current_candidate.id == feed_item.created_by) || (feed_item.checked?)
  %tr.feed-content 

    %td.gravatar
      = link_to gravatar_for(sender), sender 
    %td.micropost 
      %span(class='candidate')
        - if (current_candidate.id == feed_item.created_by) 
          = raw("<strong style='color:#2268ae;'> You </strong> sent to <strong style='color:#2268ae;'>#{receiver.first_name} #{receiver.first_last_name}</strong>")
        - else
          = raw("<strong style='color:#2268ae;'>#{sender.first_name} #{sender.first_last_name}</strong> sent to <strong style='color:#2268ae;'> You </strong>")
      %span(class='content')
        = feed_item.content
      %span(class='timestamp')
        Posted 
        = time_ago_in_words(feed_item.created_at)
        ago.
      .reply-container
    %td.micropost-delete
      - @value = "/reply/#{feed_item.created_by}"
      - if (current_candidate.id == feed_item.created_by)
        = link_to "Remove", feed_item, :method => :update, :confirm => "You sure?", :title => feed_item.content
      - else
        = label_tag :reply, t("reply"), :id => "#{feed_item.created_by}", :class=>"show_hide", :rel=>"#slidingDiv2"
- else
  %tr.feed-content.unread
    %td.gravatar
      = link_to gravatar_for(sender), sender 
    %td.micropost 
      %span(class='candidate')
        - if (current_candidate.id == feed_item.created_by) 
          = raw("<strong style='color:#2268ae;'> You </strong> sent to <strong style='color:#2268ae;'>#{receiver.first_name} #{receiver.first_last_name}</strong>")
        - else
          = raw("<strong style='color:#2268ae;'>#{sender.first_name} #{sender.first_last_name}</strong> sent to <strong style='color:#2268ae;'> You </strong>")
      %span(class='content')
        = feed_item.content
      %span(class='timestamp')
        Posted 
        = time_ago_in_words(feed_item.created_at)
        ago.
    %td.micropost-delete
      - @value = "/reply/#{feed_item.created_by}"
      - if (current_candidate.id == feed_item.created_by)
        = link_to "Remove", feed_item, :method => :update, :confirm => "You sure?", :title => feed_item.content
      - else
        = label_tag :reply, t("reply"), :id => "#{feed_item.created_by}", :class=>"show_hide", :rel=>"#slidingDiv2"



  

app/views/shared/_micropost_form.html.haml
- form_for(@micropost, :html => { :class => "micropost_form"} ) do |f|
  = render 'shared/error_messages', :object => f.object
  = f.text_area :content
  = f.submit "Submit"

app/views/shared/_sidebar.html.haml
<!-- Sidebar -->
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    = link_to 'About', '#'
  #if_subnav.divider
  %ul#nav_sub.sub_navigation
    %li= link_to 'Corporate Overview', '#'
    %li= link_to 'Clients', '#'
    %li.last= link_to 'Executive Leadership', '#'
  %img(src="http://www.4thsource.com//public/images/sidebar_about.jpg" alt="about" class="sidebar_img")
  .clear

app/views/shared/_sidebar_signed.html.haml
#sidebar
  <!-- Subnav -->
  %h4#if_sub_nav
    Profile Information
  #if_subnav.divider
    - if signed_in?
      #sidebar-profile
        #sidebar-gravatar
          =link_to("#") do
            = image_tag current_candidate.avatarurl
        #sidebar-candidate
          = current_candidate.first_name
          = current_candidate.first_last_name
          %br
      %br
    %br
    -if has_admin_role?
      %div#slidingDiv
        -if current_candidate.is_follow?(@follow_candidate_id)
          =render "following/form"
      %div#emptyDiv
      %br
      %br
      = link_to 'Return Home', root_path, :class => "profile-sub_navigation"
      %h4 "Edit as #{current_candidate.first_name} #{current_candidate.first_last_name}"
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'User Info', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
          -if !get_my_wall.nil?
            %li
              %i.iconResume
              = link_to_resume('Resume', get_my_wall.id, :action => 'resume', :class => 'profile-sub_navigation')
              %ul#nav_sub.sub_navigation
                %li
                  %i.iconSummary
                  = link_to "Profiles", url_options = { :controller => "candidates_profiles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
                %li
                  %i.iconExperience
                  = link_to_project('Projects', get_my_wall.id, :action => 'index', :class => 'profile-sub_navigation')
                %li
                  %i.iconEducation
                  = link_to_resume('Education', get_my_wall.id, :action => 'education', :class => 'profile-sub_navigation')
                %li
                  %i.iconCertification
                  = link_to_resume('Certification', get_my_wall.id, :action => 'certification', :class => 'profile-sub_navigation')
                %li
                  %i.iconExperience
                  = link_to_resume('Candidate Profiles',get_my_wall.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
                %li.last
                  %i.iconInterests
                  = link_to_resume('Languages', get_my_wall.id, :action => 'languages', :class => 'profile-sub_navigation')        
        %li
          %i.iconResume
          = link_to_candidates('Candidates', current_candidate.id, :action => 'candidates', :class => 'profile-sub_navigation')

          -if !get_wall_candidate.nil?
            %ul#nav_sub.sub_navigation
              %li
                %i.iconContact-info
                = link_to get_wall_candidate.actual_name+' profile', edit_candidate_path(get_wall_candidate), :class => "profile-sub_navigation"
              %li
                %i.iconResume
                = link_to_resume('Resume', get_wall_candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
                %ul#nav_sub.sub_navigation
                  %li
                    %i.iconSummary
                    = link_to "Profiles", url_options = { :controller => "candidates_profiles", :action => "index", :id => get_wall_candidate.id}, html_options = { :class => 'profile-sub_navigation' }                    
                  %li
                    %i.iconExperience
                    = link_to_project('Projects', get_wall_candidate.id, :action => 'index', :class => 'profile-sub_navigation')
                  %li
                    %i.iconEducation
                    = link_to_resume('Education', get_wall_candidate.id, :action => 'education', :class => 'profile-sub_navigation')
                  %li
                    %i.iconCertification
                    = link_to_resume('Certification', get_wall_candidate.id, :action => 'certification', :class => 'profile-sub_navigation')
                  %li
                    %i.iconExperience
                    = link_to_resume('Candidate Profiles',get_wall_candidate.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
                  %li.last
                    %i.iconInterests
                    = link_to_resume('Languages', get_wall_candidate.id, :action => 'languages', :class => 'profile-sub_navigation')

        -if role == SessionsHelper::SUPERADMIN
          %li
            %i.iconAdminUser
            = link_to 'Admin users',url_options = { :controller => "admin_users", :action => "index", :id => current_candidate.id.to_s}, html_options = { :class => 'profile-sub_navigation' }
        %li
          %i.iconReport
            = label_tag 'Reports', nil, :class => 'profile-sub_navigation'
          %br
          %br
          %ul#nav_sub.sub_navigation
            %li
              %i.iconInterviewer
              = link_to 'Advanced search', '/staff/' + current_candidate.id.to_s + '/report', :class => 'profile-sub_navigation'
            %li
              %i.iconIntervieweType
              = link_to 'Interviews Report', '/staff/' + current_candidate.id.to_s + '/interviews/report', :class => 'profile-sub_navigation'
            %li
              %i.iconExperience
              = link_to "Jobs", url_options = { :controller => "jobs", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconExperience
              = link_to "Match Up", url_options = { :controller => "job_match", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
        %li
          %i.iconSummary
            = label_tag 'Catalogs', nil, :class => 'profile-sub_navigation'
          %br
          %br
          %ul#nav_sub.sub_navigation
            %li
              %i.iconIntervieweType
              = link_to "Interview Types", url_options = { :controller => "interviews_types", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconInterviewer
              = link_to "Interviewers", url_options = { :controller => "interviewers", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconEducation
              = link_to 'Education Degrees', url_options = {:controller => "educ_degrees",:action => 'index', :id => current_candidate.id},  :class => 'profile-sub_navigation'
            %li
              %i.iconInterests
              = link_to 'Languages', '/staff/' + current_candidate.id.to_s + '/languages', :class => 'profile-sub_navigation'
            %li
              %i.iconCertification
              = link_to "Certifications", url_options = { :controller => "certifications", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconRolesHeadLine{:style => 'margin-top: 8px;'}
              = link_to "Roles", url_options = { :controller => "roles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Knowledges", url_options = { :controller => "tags", :action => "knowledges", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }              
            %li
              %i.iconTags
              = link_to "Tools", url_options = { :controller => "tags", :action => "tools", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconTags
              = link_to "Platforms", url_options = { :controller => "tags", :action => "technologies", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
    -else
      %ul#nav_sub.sub_navigation
        %li
          %i.iconContact-info
          = link_to 'User info', edit_candidate_path(current_candidate), :class => "profile-sub_navigation"
        %li
          %i.iconResume
          = link_to_resume('Resume', current_candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
          %ul#nav_sub.sub_navigation
            %li
              %i.iconSummary
              = link_to "Profiles", url_options = { :controller => "candidates_profiles", :action => "index", :id => current_candidate.id}, html_options = { :class => 'profile-sub_navigation' }
            %li
              %i.iconExperience
              = link_to_project('Projects', current_candidate.id, :action => 'index', :class => 'profile-sub_navigation')
            %li
              %i.iconEducation
              = link_to_resume('Education', current_candidate.id, :action => 'education', :class => 'profile-sub_navigation')
            %li
              %i.iconCertification
              = link_to_resume('Certification', current_candidate.id, :action => 'certification', :class => 'profile-sub_navigation')
            %li
              %i.iconExperience
              = link_to_resume('Candidate Profiles', current_candidate.id, :action => 'candidate_profiles', :class => 'profile-sub_navigation')
            %li.last
              %i.iconInterests
              = link_to_resume('Languages', current_candidate.id, :action => 'languages', :class => 'profile-sub_navigation')
        -if !current_candidate.interviewer_users.nil? && current_candidate.interviewer_users.count > 0
          %li
            %i.iconInterviewer
            = link_to_candidates('Candidates to interview', current_candidate.id, :action => 'candidates', :class => 'profile-sub_navigation')
            -if !get_wall_candidate.nil?
              %ul#nav_sub.sub_navigation
                %li
                  %i.iconResume
                  = link_to_resume(get_wall_candidate.actual_name+' resume', get_wall_candidate.id, :action => 'resume', :class => 'profile-sub_navigation')
    %br
    .clear

app/views/shared/_user_info.html.haml
#candidate_info
  =link_to = candidate_path(current_candidate) do
    = gravatar_for current_candidate, :size => 30 
    %span(class="candidate_name")
      = current_candidate.name  
    %span(class="microposts")
      = pluralize(current_candidate.microposts.count, "micropost")

app/views/shared/follower_feed.html.haml
-@page_results.each do |a|
  = label_tag a.content